#!/usr/bin/env bash

apt-get update
apt-get install -y --force-yes libdevice-serialport-perl libpoe-perl cpanminus fbset git make libpng-dev gcc libfreetype6-dev
cpanm install Imager::Font
cpanm install Imager::File::PNG
cpanm install Graphics::Framebuffer
cpanm install Linux::Input
cpanm install Imager::File::PNG
cpanm install Imager::Font::FT2

echo "modprobe spicc" >>/etc/rc.local
echo "fbtft_device name=odroidc_tft32 rotate=270 gpios=reset:116,dc:115 speed=32000000 cs=0" >>/etc/rc.local
echo "/bin/con2fbmap 1 2" >>/etc/rc.local
