#!/usr/bin/env bash

apt-get update
apt-get install -y --force-yes libdevice-serialport-perl libpoe-perl cpanminus fbset git make libpng-dev gcc libfreetype6-dev fonts-freefont-ttf fonts-unfonts-core screen
cpanm install Imager::Font
cpanm install Imager::File::PNG
cpanm install Graphics::Framebuffer
cpanm install Linux::Input
cpanm install Imager::File::PNG
cpanm install Imager::Font::FT2

echo "/sbin/modprobe spicc" >>/etc/rc.local
echo "/sbin/modprobe fbtft_device name=odroidc_tft32 rotate=270 gpios=reset:116,dc:115 speed=32000000 cs=0" >>/etc/rc.local
echo '(sleep 2; /bin/con2fbmap 1 2) &' >>/etc/rc.local
echo '(sleep 4; /usr/bin/screen -S zeit -d -m perl -e '"'"'chdir("/opt/zeiterfassung"); system("/bin/bash -c ".chr(34)."while true; do perl startZeiterfassung.pl; sleep 10; done;".chr(34).";"); system("/bin/stty sane"); system("/bin/bash");'"'"') &' >>/etc/rc.local

cd /opt
git clone git@git.priv.de:odroid/zeiterfassung.git
